version: '3.8'

services:
  # 1. MQTT Broker
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: hotel_mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  # 2. Custom Dashboard (Node.js)
  dashboard:
    build: ./hotel-dashboard
    container_name: hotel_dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./hotel-dashboard:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mqtt
    command: node --watch server.js

  # 3. MySQL Database
  mysql:
    image: mysql:latest
    container_name: hotel_database
    environment:
      # ดึงรหัสผ่านจากไฟล์ .env ที่เราทำไว้
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
 # 2. Node-RED (Logic & Dashboard)

 # nodered:

  #  image: nodered/node-red:latest

  #  container_name: hotel_nodered

  #  environment:

  #    - TZ=Asia/Bangkok

  #  ports:

  #    - "1880:1880"

  #  volumes:

  #    - ./nodered_data:/data

  #  restart: unless-stopped

